### ISSUE TITLE
Remove static variable

### ISSUE THREAD

**Issue by VasiletsFour** [ZizikUKR/UkrainianBrands#12]
https://github.com/ZizikUKR/UkrainianBrands/blob/8fca5886e88ec16820c185419d59d9815bfceb6c/UkrainianBrands.Api/client/src/shared/components/in-search.tsx#L19

**Comment by VasiletsFour** [comment]
Either use a hook or move it outside of a component

**Comment by Jekson949** [comment]
moved servises it outside a component
