### ISSUE TITLE
Fix filter callback

### ISSUE THREAD

**Issue by VasiletsFour** [ZizikUKR/UkrainianBrands#14]
https://github.com/ZizikUKR/UkrainianBrands/blob/8fca5886e88ec16820c185419d59d9815bfceb6c/UkrainianBrands.Api/client/src/shared/components/in-filters-popup.tsx#L65

**Comment by VasiletsFour** [comment]
selectedSizes.filter(size => size.id == sizeId)  can be reduced

**Comment by ZizikUKR** [comment]
This was already resolved
