### ISSUE TITLE
Remove return

### ISSUE THREAD

**Issue by VasiletsFour** [ZizikUKR/UkrainianBrands#15]
https://github.com/ZizikUKR/UkrainianBrands/blob/8fca5886e88ec16820c185419d59d9815bfceb6c/UkrainianBrands.Api/client/src/shared/components/in-filters-popup.tsx#L71

**Comment by VasiletsFour** [comment]
I think a return is needed here.

**Comment by ZizikUKR** [comment]
This method was already deleted
