### ISSUE TITLE
Fix service parameters 

### ISSUE THREAD

**Issue by VasiletsFour** [ZizikUKR/UkrainianBrands#9]
https://github.com/ZizikUKR/UkrainianBrands/blob/8fca5886e88ec16820c185419d59d9815bfceb6c/UkrainianBrands.Api/client/src/shared/services/auth.service.js#L19

**Comment by VasiletsFour** [comment]
Add URL to service, pass path to methods instead of URL

**Comment by ZizikUKR** [comment]
Refactored in this PR
https://github.com/ZizikUKR/UkrainianBrands/pull/17
